# Numpy Array

### Membuat Array dari Python List

In [1]:
import numpy as np

In [2]:
# integer array:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

Tidak seperti Python lists, Numpy array elemen-elemennya bertipe data sama. Apabila tipe data nya tidak sama maka Numpy akan melakuakan upcast (menyamakan ke tipe data yang lebih tinggi) misalnya integer akan upcast ke float:

In [3]:
np.array([3.14, 5, 2, 8])

array([3.14, 5.  , 2.  , 8.  ])

### Membuat Array dari Awal

Untuk membuat array yang besar, lebih efesien membuat array dari awal dengan menggunakan *routine* yang sudah terdapat di Numpy. Berikut beberapa contohnya:

In [4]:
# Membuat sebuah array bertipe integer dengan panjang 10 dan berisi semua nol
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
# Membuat array berukuran 3x5 float dan berisi 1 semua
np.ones((3,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [6]:
# Membuat 3x5 array yang berisi 3.14 semua
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [7]:
# Membuat array berurutan dimulai dari 0 dan berakhir pada 20 dan bertambah 2
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
# Membuat array dengan 5 nilai yang berjarak diatara 0 dan 1
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [10]:
# Membuat 3x3 array random
# nilai random diantara 0 dan 1
np.random.random((3,3))

array([[0.05932561, 0.04091916, 0.09820588],
       [0.83964253, 0.31467017, 0.55782939],
       [0.81527955, 0.90449454, 0.47003766]])

In [12]:
# Membuat 3x3 array dengan random bertipe integer pada interval 0,10
np.random.randint(0,10, (3,3))

array([[4, 3, 2],
       [5, 4, 2],
       [0, 5, 1]])

In [13]:
# Membuat 3x3 matriks identitas
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])